### 错误处理
1. 程序错误处理 defer + recover
```go
func text() {
	defer func() {
		err := recover() //当text函数发生错误是,错误信息会被传给recover
		if err != nil {  //错误信息不为空则打印
			fmt.Println("err = ", err)
		}
	}() // ()是调用匿名函数
	a := 0
	b := 5 / a
	fmt.Println(b)
}
func main() {
	text()
	fmt.Println("正在执行...")
}
// err =  runtime error: integer divide by zero
// 正在执行...
```
2. 自定义错误处理 errors.New
```go
func text1(name string) (err error) {
	a := strings.HasSuffix(name, "pdf") // 返回值命名
	if a == true {
		return nil
	}
	return errors.New("文件类型错误") //返回一个自定义的错误

}
func text() {
	err := text1("go语言圣经.md")
	if err != nil {
		panic(err) // 输出这个错误，并终止程序
	}
	fmt.Println("text正在执行")
}
func main() {
	text()
	fmt.Println("main正在执行...")
}
//panic: 文件类型错误
```